/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Advance Preferances": "Advance Preferances",
    "Asr": "Asr",
    "Auto Detect Location": "Auto Detect Location",
    "City Name": "City Name",
    "Credits": "Credits",
    "Done": "Done",
    "Douhr": "Douhr",
    "Fajr": "Fajr",
    "Isha": "Isha",
    "Magrib": "Magrib",
    "PTPlace": "Your City",
    "Reset": "Reset",
    "Shrouk": "Shrouk"
};


