/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Advance Preferances": "إعدادات متقدمة",
    "Asr": "العصر",
    "Auto Detect Location": "تحديد الموقع بشكل آلي",
    "City Name": "أسم المدينة",
    "Credits": "Credits",
    "Done": "Done",
    "Douhr": "الظهر",
    "Fajr": "الفجر",
    "Isha": "العشاء",
    "Magrib": "المغرب",
    "PTPlace": "مدينتك",
    "Reset": "إعادة",
    "Shrouk": "الشروق"
};



